# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |bcyb|
  
  if `VBoxManage natnetwork list | grep BCYB | wc -l` == 0
    v.customize ["natnetwork", "add", "--netname", "BCYB", "--network", "10.0.0.0/8"]
  end

  bcyb.vm.define "IPS1" do |ips1|
    ips1.vm.box = "fedora/29-cloud-base"
    ips1.vm.provider "virtualbox" do |v|
      v.gui = true
      v.name = "IPS1"
    end
    ips1.vm.provision "shell", path: "ips1.sh"
  end

  bcyb.vm.define "IPS1" do |ips1|
    ips1.vm.box = "fedora/29-cloud-base"
    ips1.vm.provider "virtualbox" do |v|
      v.gui = true
      v.name = "IPS1"
    end
    ips1.vm.provision "shell", path: "ips1.sh"
  end

  bcyb.vm.define "SRV1" do |srv1|
    srv1.vm.box = "fedora/29-cloud-base"
    srv1.vm.provider "virtualbox" do |v|
      v.gui = true
      v.name = "SRV1"
    end
    srv1.vm.provision "shell", path: "srv.sh"
  end

  bcyb.vm.define "IPS2" do |ips2|
    ips2.vm.box = "fedora/29-cloud-base"
    ips2.vm.provider "virtualbox" do |v|
      v.gui = true
      v.name = "IPS2"
    end
    ips2.vm.provision "shell", path: "ips2.sh"
  end

  bcyb.vm.define "SRV2" do |srv2|
    srv2.vm.box = "fedora/29-cloud-base"
    srv2.vm.provider "virtualbox" do |v|
      v.gui = true
      v.name = "SRV2"
    end
    srv2.vm.provision "shell", path: "srv.sh"
  end

  bcyb.vm.define "MDNS" do |mdns|
    mdns.vm.box = "ArturB/bionic64-desktop"
    mdns.vm.provider "virtualbox" do |v|
      v.gui = true
      v.name = "MDNS"
    end
    mdns.vm.provision "shell", path: "mdns.sh"
  end

end
