# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |bcyb|
  
  bcyb.vm.define "DNS" do |dns|
    dns.vm.box = "ArturB/bionic64-desktop"
    dns.vm.provider "virtualbox" do |v|
      v.gui = true
      v.name = "bcyb_DNS"
    end 
  end

  bcyb.vm.define "N2" do |n2|
    n2.vm.box = "fedora/29-cloud-base"
    n2.vm.provider "virtualbox" do |v|
      v.gui = true
      v.name = "bcyb_N2"
    end    
    n2.vm.provision "shell", path: "n2.sh"
    n2.vm.network "private_network", ip: "192.168.2.1"
  end

  bcyb.vm.define "S2" do |s2|
    s2.vm.box = "fedora/29-cloud-base"
    s2.vm.provider "virtualbox" do |v|
      v.gui = true
      v.name = "bcyb_S2"
    end    
    s2.vm.provision "shell", path: "s2.sh"
    s2.vm.network "private_network", ip: "192.168.2.2"
  end

end
