# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |snort3|
  snort3.vm.box = "fedora/29-cloud-base"
  snort3.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
    vb.name = "snort3-precompiled"
  end
  snort3.vm.provision "shell", path: "bootstrap.sh"
end
